"""CodexBackend LIVE integration over codex exec + MCP injection (env-gated).

Run:  TILLDONE_CODEX_E2E=1 uv run pytest tests/backends/test_codex_integration.py -v

Real (billed) `codex exec` calls through the ambient ~/.codex auth + gateway, driving the
localhost MCP bridge under --dangerously-bypass-approvals-and-sandbox. SKIP != PASS (T1):
gate off -> skipped; gate on -> actually executed. Effort forced low for speed.
"""

from __future__ import annotations

import os
import secrets
from pathlib import Path

import pytest

from tilldone.backends.codex import CodexBackend
from tilldone.core.contract import CompletionContract, ReturnExpectation
from tilldone.core.loop import CorePolicy, run_task
from tilldone.core.spec import AgentRunSpec
from tilldone.core.tools import ToolCall, ToolResult
from tilldone.testing.conformance import assert_protocol_invariants, collect_run

pytestmark = pytest.mark.integration

_GATE = os.environ.get("TILLDONE_CODEX_E2E") == "1"
_skip = pytest.mark.skipif(not _GATE, reason="set TILLDONE_CODEX_E2E=1 to run live Codex tests")


def _fast_backend() -> CodexBackend:
    # force low reasoning effort so live tests don't run for minutes (config default is xhigh)
    return CodexBackend(extra_config=['model_reasoning_effort="low"'])


class _StubExecutor:
    async def invoke(self, call: ToolCall) -> ToolResult:
        return ToolResult(content="ok")


@_skip
async def test_codex_e2e_tool_side_effect_nonce(tmp_path: Path):
    """RT-TOOL-1 / RT-MCP-3 / RT-FIN-1: prove the custom tool REALLY ran via the MCP bridge
    under bypass — assert its side-effect (a runtime nonce written to disk), not task success.
    The nonce is generated by the handler at call time and never appears in the prompt (W2).
    """
    nonce_file = tmp_path / "nonce.txt"
    state = {"nonce": None, "calls": 0}

    async def generate_token(call: ToolCall) -> ToolResult:
        state["calls"] += 1
        nonce = secrets.token_hex(8)        # runtime, high-entropy, NOT in the prompt
        state["nonce"] = nonce
        nonce_file.write_text(nonce)         # the side-effect under test
        return ToolResult(content=nonce)

    contract = CompletionContract(outputs=(), returns=(ReturnExpectation("token", "str", True),),
                                  todos=(), require_finish=True)
    prompt = (
        "Do all of the following in order:\n"
        "1. Call the 'generate_token' tool (no arguments) to obtain a token string.\n"
        "2. Call the 'return' tool with argument token set to EXACTLY that token string.\n"
        "3. Call the 'finish' tool."
    )
    result = await run_task(
        contract, _fast_backend(), prompt=prompt, cwd=tmp_path,
        policy=CorePolicy(max_rounds=4),
        custom_tools={"generate_token": generate_token},
    )

    # the tool actually fired its side-effect (not merely "task succeeded"):
    assert state["calls"] >= 1 and state["nonce"] is not None
    assert nonce_file.exists() and nonce_file.read_text() == state["nonce"]
    # and the model round-tripped the tool's nonce through the contract return:
    assert result == state["nonce"]


@_skip
async def test_codex_e2e_protocol_conformance(tmp_path: Path):
    """T2 conformance checker against a REAL codex exec --json event stream."""
    spec = AgentRunSpec(prompt="Reply with exactly the word ACK and nothing else.",
                        tools=(), cwd=tmp_path)
    events, outcome = await collect_run(_fast_backend(), spec, _StubExecutor())
    assert_protocol_invariants(events, outcome)
    assert outcome.resume is not None and outcome.resume.backend == "codex"
    assert outcome.resume.token.get("session_id")
